### ISSUE TITLE
error: #pragma GCC diagnostic not allowed inside functions

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#1642]
Hi,
harfbuzz 2.3.1 doesn't compile on Mac OS X 10.6 with its default compiler Apple gcc 4.2.1. It has these errors:

```
hb-blob.cc:34: warning: expected [error|warning|ignored] after �#pragma GCC diagnostic�
hb-blob.cc:37: warning: expected [error|warning|ignored] after �#pragma GCC diagnostic�
hb-dsalgs.hh:239: error: #pragma GCC diagnostic not allowed inside functions
hb-dsalgs.hh:240: error: #pragma GCC diagnostic not allowed inside functions
hb-dsalgs.hh:245: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:70: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:71: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:73: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:78: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:79: error: #pragma GCC diagnostic not allowed inside functions
hb-machinery.hh:81: error: #pragma GCC diagnostic not allowed inside functions
```

This was reported to MacPorts here: https://trac.macports.org/ticket/58258

I'm not sure if moving these pragmas outside of the functions would still do what you want. We can certainly patch this in MacPorts to remove the pragmas for old compilers if you can't make a suitable change.

**Comment by behdad** [comment]
I don't know what's wrong with my Mac setup, but I tried "make dist" again, and still get the 14-byte tarball.  Can someone build the tarball for 2.4.0 commit and send it to me to sign and upload?

**Comment by behdad** [comment]
We have dropped gcc 4.2 support.  It doesn't even support "pragma diagnostic push".  Today i'm going to merge the "iter" branch which requires C++11 and makes template uses that gcc 4.2 just cannot keep up with.  So, you're on your own I'm afraid.

**Comment by ryandesign** [comment]
Ok thanks, I'll mark the port as requiring C++11 so we're ready for that.
