### PR TITLE
meson: complete introspection build config

### LINKED ISSUE #2336: meson: introspection build fails with preprocessor error
I gave the new meson build in 2.6.5 a try and hit this:

```
[1/2] Generating HarfBuzz-0.0.gir with a meson_exe.py custom command
FAILED: src/HarfBuzz-0.0.gir
"C:/msys64/mingw64/bin/meson" "--internal" "exe" "--unpickle" "C:/msys64/home/user/git/harfbuzz/_build/meson-private/meson_exe_g-ir-scanner_7e778d51994b8b488bb6076721be0b3230214e7a.dat"
cc1.exe: warning: command line option '-fno-rtti' is valid for C++/D/ObjC++ but not for C
cc1.exe: warning: command line option '-fno-threadsafe-statics' is valid for C++/ObjC++ but not for C
cc1.exe: warning: command line option '-fvisibility-inlines-hidden' is valid for C++/ObjC++ but not for C
In file included from C:/msys64/home/user/git/harfbuzz/_build/g-ir-cpp-3yq2u_fj.c:4:
C:/msys64/home/user/git/harfbuzz/src/hb-aat-layout.h:26:2: error: #error "Include <hb-aat.h> instead."
   26 | #error "Include <hb-aat.h> instead."
      |  ^~~~~
```

### PR DESCRIPTION
**Pull request by lazka**
Pass the same config to gobject-introspection as with cmake/autotools.

This makes sure the c-include and package name is included in the gir
and also fixes the build because of the missing HB_AAT_H* defines.

Fixes #2336

### CODE REVIEW

**Comment by ebraminio** [comment]
Looks great! Thanks :)
