### ISSUE TITLE
Harfbuzz gcc requirement

### ISSUE THREAD

**Issue by rprasanth** [harfbuzz/harfbuzz#3526]
Hi Team,

Is there any minimum requirement for building Harfbuzz?
I'm trying to build with gcc-4.9.4 which fails, whereas I could build the same with gcc-5.5.
I can confirm this was due to the Gcc version, But I need to know, Whether harfbuzz has a requirement for GCC versions? kindly help

Attached fail log
[harf.log](https://github.com/harfbuzz/harfbuzz/files/8426604/harf.log)

**Comment by behdad** [comment]
Looks like gcc 5 is required according to:


https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std

If you can get it to compile by
reverting be42800fc6d90340f843fa03be1bb06b0453e519, I consider doing that.
Otherwise it is what it is.

What system has that gcc currently?

behdad
http://behdad.org/

**Comment by rprasanth** [comment]
Hi Behdad,

It seems is_trivially_copyable was not only the error, There are many changes relevant to c++11 std. 
```
error: 'is_trivially_copy_assignable' is not a member of 'std'
../src/hb-vector.hh:333:24: error: 'grow_vector' was not declared in this scope
../src/hb-vector.hh:312:48: error: 'realloc_vector' was not declared in this scope
```

is it possible to update the Document as Gcc5 as the Hard requirement for the latest versions of Harfbuzz?

**Comment by ThomasDevoogdt** [comment]
Here is a small patch to get Harfbuzz compiled for GCC 4.9. Let me know if there is interest in upstreaming it, if yes, I will create a PR for it. (Or apply the patch yourself.)

```patch
From 6906f317f929fbec6c8e39154b833f8be794634d Mon Sep 17 00:00:00 2001
From: Thomas Devoogdt <thomas.devoogdt@barco.com>
Date: Tue, 10 May 2022 10:00:06 +0200
Subject: [PATCH] fix type traits on gcc 4.9

Signed-off-by: Thomas Devoogdt <thomas.devoogdt@barco.com>
---
 src/hb-open-type.hh | 15 ++++++++++-----
 src/hb-vector.hh    | 25 +++++++++++++++++--------
 2 files changed, 27 insertions(+), 13 deletions(-)

diff --git a/src/hb-open-type.hh b/src/hb-open-type.hh
index 7e524177f..b29477fe9 100644
--- a/src/hb-open-type.hh
+++ b/src/hb-open-type.hh
@@ -35,6 +35,11 @@
 #include "hb-machinery.hh"
 #include "hb-subset.hh"
 
+#if __GNUG__ && __GNUC__ < 5
+#define IS_TRIVIALLY_COPYABLE(T) __has_trivial_copy(T)
+#else
+#define IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
+#endif
 
 namespace OT {
 
@@ -518,7 +523,7 @@ struct UnsizedArrayOf
   {
     TRACE_SANITIZE (this);
     if (unlikely (!sanitize_shallow (c, count))) return_trace (false);
-    if (!sizeof... (Ts) && std::is_trivially_copyable<Type>::value) return_trace (true);
+    if (!sizeof... (Ts) && IS_TRIVIALLY_COPYABLE(Type)) return_trace (true);
     for (unsigned int i = 0; i < count; i++)
       if (unlikely (!c->dispatch (arrayZ[i], std::forward<Ts> (ds)...)))
 	return_trace (false);
@@ -707,7 +712,7 @@ struct ArrayOf
   {
     TRACE_SANITIZE (this);
     if (unlikely (!sanitize_shallow (c))) return_trace (false);
-    if (!sizeof... (Ts) && std::is_trivially_copyable<Type>::value) return_trace (true);
+    if (!sizeof... (Ts) && IS_TRIVIALLY_COPYABLE(Type)) return_trace (true);
     unsigned int count = len;
     for (unsigned int i = 0; i < count; i++)
       if (unlikely (!c->dispatch (arrayZ[i], std::forward<Ts> (ds)...)))
@@ -835,7 +840,7 @@ struct HeadlessArrayOf
   {
     TRACE_SANITIZE (this);
     if (unlikely (!sanitize_shallow (c))) return_trace (false);
-    if (!sizeof... (Ts) && std::is_trivially_copyable<Type>::value) return_trace (true);
+    if (!sizeof... (Ts) && IS_TRIVIALLY_COPYABLE(Type)) return_trace (true);
     unsigned int count = get_length ();
     for (unsigned int i = 0; i < count; i++)
       if (unlikely (!c->dispatch (arrayZ[i], std::forward<Ts> (ds)...)))
@@ -884,7 +889,7 @@ struct ArrayOfM1
   {
     TRACE_SANITIZE (this);
     if (unlikely (!sanitize_shallow (c))) return_trace (false);
-    if (!sizeof... (Ts) && std::is_trivially_copyable<Type>::value) return_trace (true);
+    if (!sizeof... (Ts) && IS_TRIVIALLY_COPYABLE(Type)) return_trace (true);
     unsigned int count = lenM1 + 1;
     for (unsigned int i = 0; i < count; i++)
       if (unlikely (!c->dispatch (arrayZ[i], std::forward<Ts> (ds)...)))
@@ -1070,7 +1075,7 @@ struct VarSizedBinSearchArrayOf
   {
     TRACE_SANITIZE (this);
     if (unlikely (!sanitize_shallow (c))) return_trace (false);
-    if (!sizeof... (Ts) && std::is_trivially_copyable<Type>::value) return_trace (true);
+    if (!sizeof... (Ts) && IS_TRIVIALLY_COPYABLE(Type)) return_trace (true);
     unsigned int count = get_length ();
     for (unsigned int i = 0; i < count; i++)
       if (unlikely (!(*this)[i].sanitize (c, std::forward<Ts> (ds)...)))
diff --git a/src/hb-vector.hh b/src/hb-vector.hh
index 6c7d32e49..273dd7c73 100644
--- a/src/hb-vector.hh
+++ b/src/hb-vector.hh
@@ -31,6 +31,15 @@
 #include "hb-array.hh"
 #include "hb-null.hh"
 
+#if __GNUG__ && __GNUC__ < 5
+#define IS_TRIVIALLY_COPY_ASSIGNABLE(T) (__has_trivial_copy(T) && __has_trivial_assign(T))
+#define IS_TRIVIALLY_CONSTRUCTIBLE(T) __has_trivial_constructor(T)
+#define IS_TRIVIALLY_DESTRUCTIBLE(T) __has_trivial_destructor(T)
+#else
+#define IS_TRIVIALLY_COPY_ASSIGNABLE(T) std::is_trivially_copy_assignable<T>::value
+#define IS_TRIVIALLY_CONSTRUCTIBLE(T) std::is_trivially_constructible<T>::value
+#define IS_TRIVIALLY_DESTRUCTIBLE(T) std::is_trivially_destructible<T>::value
+#endif
 
 template <typename Type,
 	  bool sorted=false>
@@ -203,14 +212,14 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
   bool in_error () const { return allocated < 0; }
 
   template <typename T = Type,
-	    hb_enable_if (std::is_trivially_copy_assignable<T>::value)>
+	    hb_enable_if (IS_TRIVIALLY_COPY_ASSIGNABLE(T))>
   Type *
   realloc_vector (unsigned new_allocated)
   {
     return (Type *) hb_realloc (arrayZ, new_allocated * sizeof (Type));
   }
   template <typename T = Type,
-	    hb_enable_if (!std::is_trivially_copy_assignable<T>::value)>
+	    hb_enable_if (!IS_TRIVIALLY_COPY_ASSIGNABLE(T))>
   Type *
   realloc_vector (unsigned new_allocated)
   {
@@ -230,7 +239,7 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
   }
 
   template <typename T = Type,
-	    hb_enable_if (std::is_trivially_constructible<T>::value ||
+	    hb_enable_if (IS_TRIVIALLY_CONSTRUCTIBLE(T) ||
 			  !std::is_default_constructible<T>::value)>
   void
   grow_vector (unsigned size)
@@ -239,7 +248,7 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
     length = size;
   }
   template <typename T = Type,
-	    hb_enable_if (!std::is_trivially_constructible<T>::value &&
+	    hb_enable_if (!IS_TRIVIALLY_CONSTRUCTIBLE(T) &&
 			   std::is_default_constructible<T>::value)>
   void
   grow_vector (unsigned size)
@@ -252,14 +261,14 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
   }
 
   template <typename T = Type,
-	    hb_enable_if (std::is_trivially_destructible<T>::value)>
+	    hb_enable_if (IS_TRIVIALLY_DESTRUCTIBLE(T))>
   void
   shrink_vector (unsigned size)
   {
     length = size;
   }
   template <typename T = Type,
-	    hb_enable_if (!std::is_trivially_destructible<T>::value)>
+	    hb_enable_if (!IS_TRIVIALLY_DESTRUCTIBLE(T))>
   void
   shrink_vector (unsigned size)
   {
@@ -271,7 +280,7 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
   }
 
   template <typename T = Type,
-	    hb_enable_if (std::is_trivially_copy_assignable<T>::value)>
+	    hb_enable_if (IS_TRIVIALLY_COPY_ASSIGNABLE(T))>
   void
   shift_down_vector (unsigned i)
   {
@@ -280,7 +289,7 @@ struct hb_vector_t : std::conditional<sorted, hb_vector_t<Type, false>, hb_empty
 	     (length - i) * sizeof (Type));
   }
   template <typename T = Type,
-	    hb_enable_if (!std::is_trivially_copy_assignable<T>::value)>
+	    hb_enable_if (!IS_TRIVIALLY_COPY_ASSIGNABLE(T))>
   void
   shift_down_vector (unsigned i)
   {
-- 
2.25.1


```

**Comment by behdad** [comment]
I'm happy to do that. Can you move the definitions to `hb-meta.hh`, and name them as `hb_is_trivially_...` please? Thanks.
