### ISSUE TITLE
hb-coretext-font.cc uses `kCTFontOrientation*` unconditionally, which breaks build on < 10.8

### ISSUE THREAD

**Issue by barracuda156** [harfbuzz/harfbuzz#4968]
```
../harfbuzz-10.1.0/src/hb-coretext-font.cc:112:21: warning: narrowing conversion of 'unicode' from 'hb_codepoint_t' {aka 'unsigned int'} to 'UniChar' {aka 'short unsigned int'} [-Wnarrowing]
  112 |   UniChar ch[2] = { unicode, variation_selector };
      |                     ^~~~~~~
../harfbuzz-10.1.0/src/hb-coretext-font.cc:112:30: warning: narrowing conversion of 'variation_selector' from 'hb_codepoint_t' {aka 'unsigned int'} to 'UniChar' {aka 'short unsigned int'} [-Wnarrowing]
  112 |   UniChar ch[2] = { unicode, variation_selector };
      |                              ^~~~~~~~~~~~~~~~~~
../harfbuzz-10.1.0/src/hb-coretext-font.cc: In function 'void hb_coretext_get_glyph_h_advances(hb_font_t*, void*, unsigned int, const hb_codepoint_t*, unsigned int, hb_position_t*, unsigned int, void*)':
../harfbuzz-10.1.0/src/hb-coretext-font.cc:148:42: error: 'kCTFontOrientationHorizontal' was not declared in this scope; did you mean 'kCTFontOrientationAttribute'?
  148 |     CTFontGetAdvancesForGlyphs (ct_font, kCTFontOrientationHorizontal, cg_glyph, advances, c);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          kCTFontOrientationAttribute
../harfbuzz-10.1.0/src/hb-coretext-font.cc: In function 'void hb_coretext_get_glyph_v_advances(hb_font_t*, void*, unsigned int, const hb_codepoint_t*, unsigned int, hb_position_t*, unsigned int, void*)':
../harfbuzz-10.1.0/src/hb-coretext-font.cc:182:42: error: 'kCTFontOrientationVertical' was not declared in this scope; did you mean 'kCTFontOrientationAttribute'?
  182 |     CTFontGetAdvancesForGlyphs (ct_font, kCTFontOrientationVertical, cg_glyph, advances, c);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          kCTFontOrientationAttribute
../harfbuzz-10.1.0/src/hb-coretext-font.cc: In function 'hb_bool_t hb_coretext_get_glyph_extents(hb_font_t*, void*, hb_codepoint_t, hb_glyph_extents_t*, void*)':
../harfbuzz-10.1.0/src/hb-coretext-font.cc:231:25: warning: narrowing conversion of 'glyph' from 'hb_codepoint_t' {aka 'unsigned int'} to 'CGGlyph' {aka 'short unsigned int'} [-Wnarrowing]
  231 |   CGGlyph glyphs[1] = { glyph };
      |                         ^~~~~
```

Could we add a fallback? This code cannot compile on < 10.8, since `kCTFontOrientationVertical` and `kCTFontOrientationHorizontal` do not exist.

@behdad Could you please take a look at this?

**Comment by khaledhosny** [comment]
Something like this should fix it:
```diff
diff --git a/src/hb-coretext-font.cc b/src/hb-coretext-font.cc
index e6a02cce6..742c2fc38 100644
--- a/src/hb-coretext-font.cc
+++ b/src/hb-coretext-font.cc
@@ -36,6 +36,8 @@

 #if MAC_OS_X_VERSION_MIN_REQUIRED < 101100
 #  define kCTFontOrientationDefault kCTFontDefaultOrientation
+#  define kCTFontOrientationHorizontal kCTFontHorizontalOrientation
+#  define kCTFontOrientationVertical kCTFontVerticalOrientation
 #endif

 #define MAX_GLYPHS 64u
```

Can you try it?

**Comment by mascguy** [comment]
> Something like this should fix it:
> 
> ```diff
> diff --git a/src/hb-coretext-font.cc b/src/hb-coretext-font.cc
> index e6a02cce6..742c2fc38 100644
> --- a/src/hb-coretext-font.cc
> +++ b/src/hb-coretext-font.cc
> @@ -36,6 +36,8 @@
> 
>  #if MAC_OS_X_VERSION_MIN_REQUIRED < 101100
>  #  define kCTFontOrientationDefault kCTFontDefaultOrientation
> +#  define kCTFontOrientationHorizontal kCTFontHorizontalOrientation
> +#  define kCTFontOrientationVertical kCTFontVerticalOrientation
>  #endif
> 
>  #define MAX_GLYPHS 64u
> ```
> 
> Can you try it?

That works, thank you so much!

Can we submit a PR for this change as well?

**Comment by mascguy** [comment]
> Thanks. I committed to main.

Thank you, you folks rock!

**Comment by barracuda156** [comment]
@khaledhosny @behdad Thank you very much!

(Sorry, I did not have time yesterday to test anything myself. Will run the build today.)
