### ISSUE TITLE
meson: introspection build fails with preprocessor error

### ISSUE THREAD

**Issue by lazka** [harfbuzz/harfbuzz#2336]
I gave the new meson build in 2.6.5 a try and hit this:

```
[1/2] Generating HarfBuzz-0.0.gir with a meson_exe.py custom command
FAILED: src/HarfBuzz-0.0.gir
"C:/msys64/mingw64/bin/meson" "--internal" "exe" "--unpickle" "C:/msys64/home/user/git/harfbuzz/_build/meson-private/meson_exe_g-ir-scanner_7e778d51994b8b488bb6076721be0b3230214e7a.dat"
cc1.exe: warning: command line option '-fno-rtti' is valid for C++/D/ObjC++ but not for C
cc1.exe: warning: command line option '-fno-threadsafe-statics' is valid for C++/ObjC++ but not for C
cc1.exe: warning: command line option '-fvisibility-inlines-hidden' is valid for C++/ObjC++ but not for C
In file included from C:/msys64/home/user/git/harfbuzz/_build/g-ir-cpp-3yq2u_fj.c:4:
C:/msys64/home/user/git/harfbuzz/src/hb-aat-layout.h:26:2: error: #error "Include <hb-aat.h> instead."
   26 | #error "Include <hb-aat.h> instead."
      |  ^~~~~
```

**Comment by ebraminio** [comment]
Comparing https://github.com/harfbuzz/harfbuzz/blob/master/CMakeLists.txt#L609-L639 and https://github.com/harfbuzz/harfbuzz/blob/18fc919/src/meson.build#L564-L580 guess is obvious where the issue is coming from (those `-DHB_AAT_H` and `-DHB_AAT_H_IN` things)

@tp-m @fanc999 Feel free to have a look, I will also, essentially I should add the configuration in some CI bot, maybe this one https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L234

**Comment by lazka** [comment]
I've create a PR for this

**Comment by fanc999** [comment]
Hi,

Sorry, I didn't get to look at this earlier.  I just did a build with Meson and Visual Studio 2015 x64, and the introspection build went well.

With blessings, thank you!

**Comment by ebraminio** [comment]
Awesome! Thanks
