### ISSUE TITLE
build: `struct std::hash' in different namespace` error

### ISSUE THREAD

**Issue by kleisauke** [harfbuzz/harfbuzz#3705]
It looks like PR https://github.com/harfbuzz/harfbuzz/pull/3623 broke the build with a somewhat old GCC version (6.5.0).
<details>
  <summary>Details</summary>
  
```
[2/65] Compiling C++ object src/libharfbuzz-subset.a.p/hb-subset-input.cc.o
FAILED: src/libharfbuzz-subset.a.p/hb-subset-input.cc.o 
arm-rpi-linux-gnueabihf-g++ -Isrc/libharfbuzz-subset.a.p -Isrc -I../src -I. -I.. -I/target/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -marm -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -Os -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -fPIC -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz-subset.a.p/hb-subset-input.cc.o -MF src/libharfbuzz-subset.a.p/hb-subset-input.cc.o.d -o src/libharfbuzz-subset.a.p/hb-subset-input.cc.o -c ../src/hb-subset-input.cc
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-subset.hh:31,
                 from ../src/hb-subset-input.cc:27:
../src/hb-cplusplus.hh:170:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::shared_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-subset.hh:31,
                 from ../src/hb-subset-input.cc:27:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-subset.hh:31,
                 from ../src/hb-subset-input.cc:27:
../src/hb-cplusplus.hh:180:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::unique_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-subset.hh:31,
                 from ../src/hb-subset-input.cc:27:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
[3/65] Compiling C++ object src/libharfbuzz.a.p/hb-aat-layout.cc.o
FAILED: src/libharfbuzz.a.p/hb-aat-layout.cc.o 
arm-rpi-linux-gnueabihf-g++ -Isrc/libharfbuzz.a.p -Isrc -I../src -I. -I.. -I/target/include/freetype2 -I/target/include -I/target/include/glib-2.0 -I/target/lib/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -marm -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -Os -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -fPIC -pthread -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz.a.p/hb-aat-layout.cc.o -MF src/libharfbuzz.a.p/hb-aat-layout.cc.o.d -o src/libharfbuzz.a.p/hb-aat-layout.cc.o -c ../src/hb-aat-layout.cc
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-aat-layout.cc:28:
../src/hb-cplusplus.hh:170:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::shared_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-aat-layout.cc:28:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-aat-layout.cc:28:
../src/hb-cplusplus.hh:180:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::unique_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-aat-layout.cc:28:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
In file included from ../src/hb-kern.hh:32:0,
                 from ../src/hb-aat-layout-kerx-table.hh:31,
                 from ../src/hb-aat-layout.cc:35:
../src/hb-ot-layout-gpos-table.hh:50:117: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 PosLookup::dispatch_recurse_func<hb_closure_lookups_context_t> (hb_closure_lookups_context_t *c, unsigned this_index)
                                                                                                                     ^
In file included from ../src/OT/Layout/GPOS.hh:7:0,
                 from ../src/hb-ot-layout-gpos-table.hh:32,
                 from ../src/hb-kern.hh:32,
                 from ../src/hb-aat-layout-kerx-table.hh:31,
                 from ../src/hb-aat-layout.cc:35:
../src/OT/Layout/GPOS/PosLookup.hh:62:39: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/hb-kern.hh:32:0,
                 from ../src/hb-aat-layout-kerx-table.hh:31,
                 from ../src/hb-aat-layout.cc:35:
../src/hb-ot-layout-gpos-table.hh:57:121: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 inline bool PosLookup::dispatch_recurse_func<hb_ot_apply_context_t> (hb_ot_apply_context_t *c, unsigned int lookup_index)
                                                                                                                         ^
In file included from ../src/OT/Layout/GPOS.hh:7:0,
                 from ../src/hb-ot-layout-gpos-table.hh:32,
                 from ../src/hb-kern.hh:32,
                 from ../src/hb-aat-layout-kerx-table.hh:31,
                 from ../src/hb-aat-layout.cc:35:
../src/OT/Layout/GPOS/PosLookup.hh:62:39: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                       ^~~~~~~~~~~~~~~~~~~~~
[4/65] Compiling C++ object src/libharfbuzz-subset.a.p/hb-subset-plan.cc.o
FAILED: src/libharfbuzz-subset.a.p/hb-subset-plan.cc.o 
arm-rpi-linux-gnueabihf-g++ -Isrc/libharfbuzz-subset.a.p -Isrc -I../src -I. -I.. -I/target/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -marm -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard -Os -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -fPIC -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz-subset.a.p/hb-subset-plan.cc.o -MF src/libharfbuzz-subset.a.p/hb-subset-plan.cc.o.d -o src/libharfbuzz-subset.a.p/hb-subset-plan.cc.o -c ../src/hb-subset-plan.cc
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-subset-plan.hh:30,
                 from ../src/hb-subset-plan.cc:27:
../src/hb-cplusplus.hh:170:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::shared_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-subset-plan.hh:30,
                 from ../src/hb-subset-plan.cc:27:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
In file included from ../src/hb.hh:473:0,
                 from ../src/hb-subset-plan.hh:30,
                 from ../src/hb-subset-plan.cc:27:
../src/hb-cplusplus.hh:180:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<hb::unique_ptr<T>>
             ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/basic_string.h:5655:0,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/string:52,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/stdexcept:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/array:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/tuple:39,
                 from /root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/functional:55,
                 from ../src/hb-cplusplus.hh:35,
                 from ../src/hb.hh:473,
                 from ../src/hb-subset-plan.hh:30,
                 from ../src/hb-subset-plan.cc:27:
/root/tools/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/include/c++/6.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^~~~
In file included from ../src/hb-subset-plan.cc:34:0:
../src/hb-ot-layout-gpos-table.hh:50:117: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 PosLookup::dispatch_recurse_func<hb_closure_lookups_context_t> (hb_closure_lookups_context_t *c, unsigned this_index)
                                                                                                                     ^
In file included from ../src/OT/Layout/GPOS.hh:7:0,
                 from ../src/hb-ot-layout-gpos-table.hh:32,
                 from ../src/hb-subset-plan.cc:34:
../src/OT/Layout/GPOS/PosLookup.hh:62:39: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/hb-subset-plan.cc:34:0:
../src/hb-ot-layout-gpos-table.hh:57:121: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 inline bool PosLookup::dispatch_recurse_func<hb_ot_apply_context_t> (hb_ot_apply_context_t *c, unsigned int lookup_index)
                                                                                                                         ^
In file included from ../src/OT/Layout/GPOS.hh:7:0,
                 from ../src/hb-ot-layout-gpos-table.hh:32,
                 from ../src/hb-subset-plan.cc:34:
../src/OT/Layout/GPOS/PosLookup.hh:62:39: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GPOS_impl::PosLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                       ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/hb-subset-plan.cc:35:0:
../src/hb-ot-layout-gsub-table.hh:64:119: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GSUB::SubstLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 SubstLookup::dispatch_recurse_func<hb_closure_lookups_context_t> (hb_closure_lookups_context_t *c, unsigned this_index)
                                                                                                                       ^
In file included from ../src/OT/Layout/GSUB/GSUB.hh:7:0,
                 from ../src/hb-ot-layout-gsub-table.hh:32,
                 from ../src/hb-subset-plan.cc:35:
../src/OT/Layout/GSUB/SubstLookup.hh:186:46: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GSUB::SubstLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static inline typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                              ^~~~~~~~~~~~~~~~~~~~~
In file included from ../src/hb-subset-plan.cc:35:0:
../src/hb-ot-layout-gsub-table.hh:71:123: error: specialization of 'template<class context_t> static typename context_t::return_t OT::Layout::GSUB::SubstLookup::dispatch_recurse_func(context_t*, unsigned int)' in different namespace [-fpermissive]
 inline bool SubstLookup::dispatch_recurse_func<hb_ot_apply_context_t> (hb_ot_apply_context_t *c, unsigned int lookup_index)
                                                                                                                           ^
In file included from ../src/OT/Layout/GSUB/GSUB.hh:7:0,
                 from ../src/hb-ot-layout-gsub-table.hh:32,
                 from ../src/hb-subset-plan.cc:35:
../src/OT/Layout/GSUB/SubstLookup.hh:186:46: error:   from definition of 'template<class context_t> static typename context_t::return_t OT::Layout::GSUB::SubstLookup::dispatch_recurse_func(context_t*, unsigned int)' [-fpermissive]
   static inline typename context_t::return_t dispatch_recurse_func (context_t *c, unsigned int lookup_index);
                                              ^~~~~~~~~~~~~~~~~~~~~
../src/hb-subset-plan.cc: In function 'hb_subset_plan_t* hb_subset_plan_create_or_fail(hb_face_t*, const hb_subset_input_t*)':
../src/hb-subset-plan.cc:569:88: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   if (plan->check_success (plan->gsub_langsys = hb_object_create<script_langsys_map> ()))
                                                                                        ^
../src/hb-subset-plan.cc:571:88: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   if (plan->check_success (plan->gpos_langsys = hb_object_create<script_langsys_map> ()))
                                                                                        ^
ninja: build stopped: subcommand failed.
```
</details>

Full build log: https://github.com/lovell/sharp-libvips/runs/7210917753.
