### ISSUE TITLE
use of undeclared identifiers 'kCTFontOpenTypeFeatureTag' 'kCTFontOpenTypeFeatureValue'

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#2452]
harfbuzz 2.6.7 [fails to build on OS X 10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/120521/steps/install-port/logs/stdio) and earlier:

```
libtool: compile:  /opt/local/bin/clang++-mp-9.0 -DHAVE_CONFIG_H -I. -I.. -pthread -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -fno-rtti -pipe -Os -DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR -stdlib=libc++ -arch x86_64 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -MT libharfbuzz_subset_la-hb-ot-cff2-table.lo -MD -MP -MF .deps/libharfbuzz_subset_la-hb-ot-cff2-table.Tpo -c hb-ot-cff2-table.cc  -fno-common -DPIC -o .libs/libharfbuzz_subset_la-hb-ot-cff2-table.o
mv -f .deps/libharfbuzz_la-hb-static.Tpo .deps/libharfbuzz_la-hb-static.Plo
/bin/sh ../libtool  --tag=CXX   --mode=compile /opt/local/bin/clang++-mp-9.0 -DHAVE_CONFIG_H -I. -I..  -pthread -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16        -I/opt/local/include  -fno-rtti -pipe -Os -DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR -stdlib=libc++ -arch x86_64 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -MT libharfbuzz_subset_la-hb-subset-cff-common.lo -MD -MP -MF .deps/libharfbuzz_subset_la-hb-subset-cff-common.Tpo -c -o libharfbuzz_subset_la-hb-subset-cff-common.lo `test -f 'hb-subset-cff-common.cc' || echo './'`hb-subset-cff-common.cc
hb-coretext.cc:588:8: error: use of undeclared identifier 'kCTFontOpenTypeFeatureTag'
              kCTFontOpenTypeFeatureTag,
              ^
libtool: compile:  /opt/local/bin/clang++-mp-9.0 -DHAVE_CONFIG_H -I. -I.. -pthread -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -fno-rtti -pipe -Os -DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR -stdlib=libc++ -arch x86_64 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -MT libharfbuzz_subset_la-hb-static.lo -MD -MP -MF .deps/libharfbuzz_subset_la-hb-static.Tpo -c hb-static.cc  -fno-common -DPIC -o .libs/libharfbuzz_subset_la-hb-static.o
hb-coretext.cc:589:8: error: use of undeclared identifier 'kCTFontOpenTypeFeatureValue'
              kCTFontOpenTypeFeatureValue
              ^
hb-coretext.cc:596:22: error: invalid application of 'sizeof' to an incomplete type 'CFTypeRef []'
            static_assert ((ARRAY_LENGTH_CONST (keys) == ARRAY_LENGTH_CONST (values)), "");
                            ^~~~~~~~~~~~~~~~~~~~~~~~~
./hb-algs.hh:595:59: note: expanded from macro 'ARRAY_LENGTH_CONST'
#define ARRAY_LENGTH_CONST(__array) ((signed int) (sizeof (__array) / sizeof (__array[0])))
                                                          ^~~~~~~~~
hb-coretext.cc:600:14: error: no matching function for call to 'ARRAY_LENGTH'
                                                       ARRAY_LENGTH (keys),
                                                       ^~~~~~~~~~~~
./hb-algs.hh:593:28: note: candidate template ignored: could not match 'const Type [n]' against 'CFTypeRef []'
static inline unsigned int ARRAY_LENGTH (const Type (&)[n]) { return n; }
                           ^
libtool: compile:  /opt/local/bin/clang++-mp-9.0 -DHAVE_CONFIG_H -I. -I.. -pthread -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -fno-rtti -pipe -Os -DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR -stdlib=libc++ -arch x86_64 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -MT libharfbuzz_subset_la-hb-subset-cff-common.lo -MD -MP -MF .deps/libharfbuzz_subset_la-hb-subset-cff-common.Tpo -c hb-subset-cff-common.cc  -fno-common -DPIC -o .libs/libharfbuzz_subset_la-hb-subset-cff-common.o
4 errors generated.
```

[kCTFontOpenTypeFeatureTag](https://developer.apple.com/documentation/coretext/kctfontopentypefeaturetag) and [kCTFontOpenTypeFeatureValue](https://developer.apple.com/documentation/coretext/kctfontopentypefeaturevalue) were introduced in OS X 10.10.

**Comment by khaledhosny** [comment]
The code in question is guarded with:
https://github.com/harfbuzz/harfbuzz/blob/d6ddb232fc9b8c3a04398360a1d3a0b7931033e3/src/hb-coretext.cc#L576-L595

Is there something else/more that we should check for here?

**Comment by ryandesign** [comment]
The correct value of `MAC_OS_X_VERSION_MIN_REQUIRED` for OS X 10.10 os `101000` not `1010`. (`1010` is the value for Mac OS X 10.1.)

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2453
