### ISSUE TITLE
Link failures after d58bc8c94d01dfe2a24e8c1c1e03d2ff6a9fd012

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#5704]
```
ninja: Entering directory `build'
[27/29] Linking target src/libharfbuzz-subset.so.0.61230.0
FAILED: src/libharfbuzz-subset.so.0.61230.0 
cc  -o src/libharfbuzz-subset.so.0.61230.0 src/libharfbuzz-subset.so.0.61230.0.p/hb-number.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-ot-cff1-table.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-ot-cff2-table.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-static.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-cff-common.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-cff1.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-cff2.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-input.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-instancer-iup.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-instancer-solver.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-plan.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-plan-layout.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-plan-var.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-serialize.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-layout.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-var.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-cff.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-color.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-other.cc.o src/libharfbuzz-subset.so.0.61230.0.p/graph_gsubgpos-context.cc.o src/libharfbuzz-subset.so.0.61230.0.p/hb-subset.cc.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,-soname,libharfbuzz-subset.so.0 -Bsymbolic-functions '-Wl,-rpath,$ORIGIN/:$ORIGIN/rust' -Wl,--start-group src/libharfbuzz.so.0.61230.0 -lm -Wl,--end-group
/usr/bin/ld: src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-plan-layout.cc.o: in function `OT::apply_lookup(OT::hb_ot_apply_context_t*, unsigned int, unsigned int, OT::LookupRecord const*, unsigned int)':
/usr/local/google/home/drott/dev/harfbuzz/build/../src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:1799:(.text+0x94d): undefined reference to `hb_buffer_t::move_to(unsigned int)'
/usr/bin/ld: /usr/local/google/home/drott/dev/harfbuzz/build/../src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:1905:(.text+0xc43): undefined reference to `hb_buffer_t::move_to(unsigned int)'
/usr/bin/ld: src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-serialize.cc.o: in function `OT::apply_lookup(OT::hb_ot_apply_context_t*, unsigned int, unsigned int, OT::LookupRecord const*, unsigned int)':
/usr/local/google/home/drott/dev/harfbuzz/build/../src/graph/../hb-ot-layout-gsubgpos.hh:1799:(.text+0x990): undefined reference to `hb_buffer_t::move_to(unsigned int)'
/usr/bin/ld: /usr/local/google/home/drott/dev/harfbuzz/build/../src/graph/../hb-ot-layout-gsubgpos.hh:1905:(.text+0xc86): undefined reference to `hb_buffer_t::move_to(unsigned int)'
/usr/bin/ld: src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-layout.cc.o: in function `OT::apply_lookup(OT::hb_ot_apply_context_t*, unsigned int, unsigned int, OT::LookupRecord const*, unsigned int)':
/usr/local/google/home/drott/dev/harfbuzz/build/../src/graph/../hb-ot-layout-gsubgpos.hh:1799:(.text+0xe89): undefined reference to `hb_buffer_t::move_to(unsigned int)'
/usr/bin/ld: src/libharfbuzz-subset.so.0.61230.0.p/hb-subset-table-layout.cc.o:/usr/local/google/home/drott/dev/harfbuzz/build/../src/graph/../hb-ot-layout-gsubgpos.hh:1905: more undefined references to `hb_buffer_t::move_to(unsigned int)' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

On a local meson build that has the fontations backend enabled, tests disabled, otherwise normally configured.

Bisected to d58bc8c94d01dfe2a24e8c1c1e03d2ff6a9fd012

**Comment by behdad** [comment]
Thanks @drott. Can you see if the commit I pushed fixes this?
