### ISSUE TITLE
Building with `HB_NO_MATH` is currently broken

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#5265]
I’m trying to update harfbuzzjs to the latest HarfBuzz version. 11.0.1 fails because of the issue fixed in d9304b69e08ca8a78a38ebf249d0663b593d596d, and main branch fails with:
```
In file included from harfbuzz/src/harfbuzz-subset.cc:60:
In file included from harfbuzz/src/hb-subset-plan.cc:47:
harfbuzz/src/hb-ot-math-table.hh:1110:52: error: no member named 'MATH' in 'hb_ot_face_t'
 1110 |     switch HB_CODEPOINT_ENCODE3 (font->face->table.MATH.get_blob ()->length,
      |                                  ~~~~~~~~~~~~~~~~~ ^
harfbuzz/src/OT/Var/VARC/../../../hb-algs.hh:216:51: note: expanded from macro 'HB_CODEPOINT_ENCODE3'
  216 | #define HB_CODEPOINT_ENCODE3(x,y,z) (((uint64_t) (x) << 42) | ((uint64_t) (y) << 21) | (uint64_t) (z))
      |                                                   ^
1 error generated.
```

This is because it is building with `HB_TINY` which sets `HB_NO_MATH`. It does not look like subsetting code respect `HB_NO_MATH` in any way, but I also don’t understand why it is failing now (after #5250), but not earlier.

**Comment by behdad** [comment]
Because before `table.MATH` was not being accessed anywhere.

**Comment by behdad** [comment]
Just ifdef it out.

**Comment by khaledhosny** [comment]
It feels funny to have an `ifndef HB_NO_MATH` in `hb-ot-math-table.hh` file...
