### ISSUE TITLE
No longer builds with HB_NO_DRAW since 11.2.0

### ISSUE THREAD

**Issue by a20dev** [harfbuzz/harfbuzz#5313]
Undefined symbols for architecture arm64:
```
  "hb_draw_extents_get_funcs()", referenced from:
      hb_font_t::get_glyph_extents(unsigned int, hb_glyph_extents_t*, bool) in hb-font.o
```

or:
````
hb-font.o: in function `hb_font_paint_glyph_or_fail_default(hb_font_t*, void*, unsigned int, hb_paint_funcs_t*, void*, unsigned int, unsigned int, void*)':
hb-font.cc:(.text+0x29ec): undefined reference to `hb_paint_push_transform'
````

depending on the OS.
