### ISSUE TITLE
Build: Undefined symbols for architecture x86_64 -- "OT::KernOT::SubTableWrapper::min_size" and "OT::KernAAT::SubTableWrapper::min_size"

### ISSUE THREAD

**Issue by dgdy9hvz** [harfbuzz/harfbuzz#853]
When building HarfBuzz 1.7.5, `make` was terminated with error messages saying that "OT::KernOT::SubTableWrapper::min_size" and "OT::KernAAT::SubTableWrapper::min_size" are undefined symbols for architecture x86_64.

### I did the following

export PKG_CONFIG='/opt/pkg-config/bin/pkg-config'
export PKG_CONFIG_PATH='/opt/pkg-config/lib/pkgconfig'
./configure
make

### Actual Result

`make` was terminated with the following error messages.

      GEN      libharfbuzz.la
    Undefined symbols for architecture x86_64:
      "OT::KernOT::SubTableWrapper::min_size", referenced from:
          OT::KernTable<OT::KernOT>::sanitize(OT::hb_sanitize_context_t*) const in libharfbuzz_la-hb-ot-font.o
      "OT::KernAAT::SubTableWrapper::min_size", referenced from:
          OT::KernSubTableWrapper<OT::KernAAT::SubTableWrapper>::sanitize(OT::hb_sanitize_context_t*) const  in libharfbuzz_la-hb-ot-font.o
    ld: symbol(s) not found for architecture x86_64
    collect2: ld returned 1 exit status
    make[4]: *** [libharfbuzz.la] Error 1
    make[3]: *** [all-recursive] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

### Environment

HarfBuzz 1.7.5
Mac OS X
Intel 64-bit

**Comment by behdad** [comment]
That's weird. I have no idea why that would happen.

**Comment by ebraminio** [comment]
Thank you for the report. I have also the same configuration and we have a build bot with a similar environment and we can not reproduce this, both from release and the repo. I guess we need some more info like macOS and Xcode, and are you using `llvm-clang`? I tried that also here and build had no issue.

**Comment by ryandesign** [comment]
The MacPorts project also received a bug report about this; see https://trac.macports.org/ticket/55507. It was on OS X Lion v10.7.5 with Xcode's llvm-gcc-4.2 compiler. I was able to reproduce the issue on macOS Sierra v10.12.6 when using llvm-gcc-4.2 as installed by MacPorts. It compiles fine with clang and gcc-4.2.

**Comment by ebraminio** [comment]
Thank @ryandesign, unfortunately I can't install it on my High Sierra machine but it says it can't be installed also on Sierra also? @dgdy9hvz are your recipe for this is the same?

```
➜  ~ sudo port install llvm-gcc42
--->  Fetching distfiles for llvm-gcc42
Error: llvm-gcc42 is not supported on macOS Sierra or newer.
Error: Failed to fetch llvm-gcc42: unsupported platform
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_lang_llvm-gcc42/llvm-gcc42/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port llvm-gcc42 failed
```

**Comment by ryandesign** [comment]
It's true that the llvm-gcc42 port prevents its installation on Sierra and later. The main reason for this is that it that this compiler is old and does not understand some directives used in modern macOS SDKs, but as long as you're not using those parts of the macOS SDK (which harfbuzz isn't) it should still work as well as it used to, and having it installed on a modern system is more convenient for reproducing problems with older compilers than having to find an old system to test on.

The other reason its installation is prevented is that it uses the old libstdc++ library (rather than the newer libc++ one) and modern versions of clang print a warning when this is the case. And the llvm-gcc42 build system uses the `-Werror` flag, which turns that warning into an error.

You can bypass the restriction by first manually installing llvm-gcc42's dependencies:

    sudo port install cctools ld64 gcc_select

And then installing llvm-gcc42 by overriding the OS version number, and using the non-recursive flag to ensure MacPorts doesn't replace any of your other existing ports with old-OS versions:

    sudo port -n install llvm-gcc42 os.major=15

This may not be supported by the MacPorts maintainer of llvm-gcc42, but "not supported" doesn't mean it won't work (just that Jeremy doesn't want your bug reports if it doesn't).

Similarly, MacPorts also has the apple-gcc42 port available, if you ever want to test with the Apple-modified version of gcc 4.2.1 that was used on Mac OS X Snow Leopard v10.6.8.

**Comment by ebraminio** [comment]
Very sorry that for some reasons I can't install it locally but this should have some easy solution I'd guess, can you test one of these to see if it can fix the issue,

```diff
diff --git a/src/hb-ot-kern-table.hh b/src/hb-ot-kern-table.hh
index 368f547..f515607 100644
--- a/src/hb-ot-kern-table.hh
+++ b/src/hb-ot-kern-table.hh
@@ -258,6 +258,7 @@ struct KernOT : KernTable<KernOT>

   static const uint16_t VERSION = 0x0000u;

+  public:
   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
     friend struct KernSubTableWrapper<SubTableWrapper>;
@@ -298,6 +299,7 @@ struct KernAAT : KernTable<KernAAT>

   static const uint32_t VERSION = 0x00010000u;

+  public:
   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
     friend struct KernSubTableWrapper<SubTableWrapper>;
```

Or,
```diff
diff --git a/src/hb-ot-kern-table.hh b/src/hb-ot-kern-table.hh
index 368f547..01c4723 100644
--- a/src/hb-ot-kern-table.hh
+++ b/src/hb-ot-kern-table.hh
@@ -260,6 +260,7 @@ struct KernOT : KernTable<KernOT>

   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
+    friend struct KernTable<KernOT>;
     friend struct KernSubTableWrapper<SubTableWrapper>;

     enum coverage_flags_t {
@@ -300,6 +301,7 @@ struct KernAAT : KernTable<KernAAT>

   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
+    friend struct KernTable<KernAAT>;
     friend struct KernSubTableWrapper<SubTableWrapper>;

     enum coverage_flags_t {
```

Or,

```
diff --git a/src/hb-ot-kern-table.hh b/src/hb-ot-kern-table.hh
index 368f547..9e3c898 100644
--- a/src/hb-ot-kern-table.hh
+++ b/src/hb-ot-kern-table.hh
@@ -260,7 +260,8 @@ struct KernOT : KernTable<KernOT>

   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
-    friend struct KernSubTableWrapper<SubTableWrapper>;
+    friend struct KernTable;
+    friend struct KernSubTableWrapper;

     enum coverage_flags_t {
       COVERAGE_DIRECTION_FLAG  = 0x01u,
@@ -300,7 +301,8 @@ struct KernAAT : KernTable<KernAAT>

   struct SubTableWrapper : KernSubTableWrapper<SubTableWrapper>
   {
-    friend struct KernSubTableWrapper<SubTableWrapper>;
+    friend struct KernTable;
+    friend struct KernSubTableWrapper;

     enum coverage_flags_t {
       COVERAGE_DIRECTION_FLAG  = 0x80u
```

The code there is somehow unnecessary complicated, #835 was proposed to fix it altogether but I hope we can fix your case on the meanwhile.

**Comment by behdad** [comment]
> The code there is somehow unnecessary complicated, #835 was proposed to fix it altogether but I hope we can fix your case on the meanwhile.

I don't see how you can simplify it without code duplication.

**Comment by ebraminio** [comment]
> I don't see how you can simplify it without code duplication.

You are absolutely right. So I hope we can find some solution for this. I like to install the compiler on my machine but it has lots of dependency and my machine is already tight on disk space.

**Comment by ebraminio** [comment]
I've contacted CircleCI for their macOS access, that way I can use their environment without `sudo` installing those packages and eventually add a test bot for that environment also!

**Comment by ebraminio** [comment]
@ryandesign Thanks for the great instructions! I think I have a fix for this #899 :)
