### ISSUE TITLE
build failure on OS X

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#2928]
The GTK ci build on macOS just failed in the harfbuzz subproject:

https://gitlab.gnome.org/GNOME/gtk/-/jobs/1235674

```
../subprojects/harfbuzz/src/hb-ot-layout-common.hh:1427:20: error: no matching member function for call to 'add_sorted_array'
  { return glyphs->add_sorted_array (glyphArray.as_array ()); }
           ~~~~~~~~^~~~~~~~~~~~~~~~
```

**Comment by ZanderBrown** [comment]
Also seeing this on fc33 (via jhbuild)
```
../../../../jhbuild/checkout/harfbuzz/src/hb-ot-layout-common.hh:1427:37: error: no matching function for call to ‘hb_set_digest_combiner_t<hb_set_digest_lowest_bits_t<long unsigned int, 4>, hb_set_digest_combiner_t<hb_set_digest_lowest_bits_t<long unsigned int, 0>, hb_set_digest_lowest_bits_t<long unsigned int, 9> > >::add_sorted_array(hb_sorted_array_t<const OT::HBGlyphID>)’
 1427 |   { return glyphs->add_sorted_array (glyphArray.as_array ()); }
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by alatiera** [comment]
seems it was introduced by 092094f7055c1632e9bdf2c07f16e984a88a65ec

**Comment by behdad** [comment]
Sorry all. Will get on it soon.

**Comment by behdad** [comment]
Oops. Sorry. Should be fixed.
