### ISSUE TITLE
error: use of undeclared identifier 'CTFontManagerCreateFontDescriptorsFromData'; did you mean 'CTFontManagerCreateFontDescriptorFromData'?

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#5354]
[MacPorts users report](https://trac.macports.org/ticket/71575#comment:16) harfbuzz 11.2.1 fails to build on macOS 10.13 and 10.14 only (not earlier nor later versions):

```
../harfbuzz-11.2.1/src/hb-coretext.cc:215:31: error: use of undeclared identifier 'CTFontManagerCreateFontDescriptorsFromData'; did you mean 'CTFontManagerCreateFontDescriptorFromData'?
    auto ct_font_desc_array = CTFontManagerCreateFontDescriptorsFromData (CFDataCreate (kCFAllocatorDefault, (const UInt8 *) blob_data, blob_length));
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              CTFontManagerCreateFontDescriptorFromData
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontManager.h:98:31: note: 'CTFontManagerCreateFontDescriptorFromData' declared here
CTFontDescriptorRef _Nullable CTFontManagerCreateFontDescriptorFromData(
                              ^
```

Harfbuzz code only uses this function on macOS 10.13 and later:

https://github.com/harfbuzz/harfbuzz/blob/a9c2c635189d9055c216eaaf3fc4535e811e5807/src/hb-coretext.cc#L208-L215

[Apple documentation says](https://developer.apple.com/documentation/coretext/ctfontmanagercreatefontdescriptorsfromdata(_:)) this function is available in macOS 10.13 and later. However, looking at the actual SDKs, while the symbol is in the CoreText library as of 10.13, it is not in the CTFontManager.h header until 10.15.

I guess the options are 1. to declare a prototype for `CTFontManagerCreateFontDescriptorsFromData` if using a macOS ≥ 10.13 < 10.15 SDK, or 2. not to use the function when using a < 10.15 SDK.

It should be fine to use the function if building with a ≥ 10.15 SDK and using a ≥ 10.13 deployment target, so make sure to properly distinguish between `__MAC_OS_X_VERSION_MIN_REQUIRED` (which relates to the deployment target) vs `__MAC_OS_X_VERSION_MAX_ALLOWED` (which relates to the SDK version).

**Comment by behdad** [comment]
> It should be fine to use the function if building with a ≥ 10.15 SDK and using a ≥ 10.13 deployment target, so make sure to properly distinguish between `__MAC_OS_X_VERSION_MIN_REQUIRED` (which relates to the deployment target) vs `__MAC_OS_X_VERSION_MAX_ALLOWED` (which relates to the SDK version).

This part I don't know how to do. Feel like sending a PR? Thanks.

**Comment by mascguy** [comment]
As a quick fix, we used the following patch in MacPorts:

https://raw.githubusercontent.com/macports/macports-ports/refs/heads/master/graphics/harfbuzz/files/patch-coretext-ctfontmgr-10.15.diff

Though that only checks for `__MAC_OS_X_VERSION_MIN_REQUIRED >= 101500`.

@ryandesign Ryan, your thoughts on this?

**Comment by behdad** [comment]
Fixed. Thanks.
